export const copy = {
  appName: "Pixelanea",
  tagline: "Make pixel art. Keep it local.",
  projectPlaceholder: "Untitled project",
  palettePlaceholder: "Palette swatches will appear here.",
  frameStripPlaceholder: "Frame thumbnails",
  apiConnected: "API connected",
  apiVersion: (version: string) => `Server v${version}`,
  statusChecking: "Checking connection…",
  statusSaved: "All changes saved",
  statusUnsaved: "Unsaved changes",
  statusSaving: "Saving…",
  statusSyncError: "Couldn't save changes. Try again.",
  statusUnsavedIndicator: "Unsaved",
  zoomControlsLabel: "Canvas zoom",
  zoomIn: "Zoom in",
  zoomOut: "Zoom out",
  zoomFit: "Fit canvas to view",
  hoverCell: (x: number, y: number) => `Cell ${x}, ${y}`,
  hoverCellNone: "—",
  undo: "Undo",
  redo: "Redo",
  undoRedoToolbarLabel: "Edit history",
  paletteAddColor: "Add color",
  paletteEditColor: "Edit color",
  paletteAddColorTitle: "Add color",
  paletteEditColorTitle: "Edit color",
  paletteAddColorDescription:
    "Pick a color, then click Save color to add it to your palette. Click Save palette to store changes in your project.",
  paletteEditColorDescription:
    "Pick a new color, then click Save color to update the swatch. Click Save palette to store changes in your project.",
  paletteSaveColor: "Save color",
  paletteSavePalette: "Save palette",
  paletteSavePaletteDescription:
    "Save palette changes to your project. Editing colors only updates the panel until you save.",
  paletteColorPickerLabel: "Color picker",
  paletteCancel: "Cancel",
  paletteRemoveColor: "Remove color",
  paletteRemoveInUseTitle: "Remove this color?",
  paletteRemoveInUseDescription:
    "Some pixels on the canvas use this color. Removing it will clear those pixels.",
  paletteRemoveConfirm: "Remove color",
  paletteRemoveCancel: "Keep color",
  paletteDefaultNewColor: "#808080",
  paletteLock: "Lock palette",
  paletteUnlock: "Unlock palette",
  paletteLockDescription:
    "When locked, only palette colors can be painted. Eyedropper still works.",
  paletteShadingSectionLabel: "Shading palettes",
  paletteShadingStylesLabel: "Lighting style",
  paletteShadingShadesLabel: "Generated shades",
  paletteShadingStyleCellShading: "Cell-shading",
  paletteShadingStyleLighting: "Lighting",
  paletteShadingStyleDark: "Dark",
  paletteShadingShadeLabel: (index: number, hex: string) =>
    `Shade ${index}, ${hex}`,
  paletteShadingInvalidColor: "Enter a valid color to generate shades.",
  colorFiltersSectionLabel: "Color filters",
  colorFiltersOverlayLabel: "Color overlay",
  colorFiltersOverlayEnabled: "Enable overlay",
  colorFiltersOverlayColorLabel: "Overlay color",
  colorFiltersOverlayOpacityLabel: "Overlay opacity",
  colorFiltersOverlayOpacityValue: (percent: number) => `${percent}%`,
  colorFiltersLightingLabel: "Lighting points",
  colorFiltersPlaceLighting: "Place lighting",
  colorFiltersPlaceLightingOn: "Click canvas to place",
  colorFiltersPlaceLightingOff: "Place lighting off",
  colorFiltersLightingPointLabel: (index: number) => `Lighting ${index + 1}`,
  colorFiltersLightingRadiusLabel: "Radius (cells)",
  colorFiltersLightingIntensityLabel: "Intensity",
  colorFiltersRemoveLighting: "Remove",
  colorFiltersApply: "Apply to frame",
  colorFiltersReset: "Reset filters",
  colorFiltersApplyHint:
    "Preview is non-destructive. Apply bakes the look into the current frame pixels.",
  palettePresetsLabel: "Presets",
  palettePresetRetro: "Retro",
  palettePresetGameboy: "Gameboy",
  palettePresetMonochrome: "Monochrome",
  animationPlay: "Play animation",
  animationPause: "Pause animation",
  animationFps: "Animation speed",
  animationFpsValue: (fps: number) => `${fps} fps`,
  animationLoop: "Loop animation",
  animationLoopOn: "Loop on",
  animationLoopOff: "Loop off",
  animationOnionSkin: "Onion skin",
  animationOnionSkinOn: "Onion skin on",
  animationOnionSkinOff: "Onion skin off",
  frameThumbnail: (index: number) => `Frame ${index + 1}`,
  frameStripLabel: "Frame strip",
  frameDuplicateTitle: "Duplicate frames",
  frameDuplicateDescription:
    "Expand this project to 8, 16, or 32 frames for animation. Choose whether to copy the current art into every frame or keep other frames blank.",
  frameDuplicateFillCopy: "Copy art to all frames",
  frameDuplicateFillCopyHint: "Every frame starts with the same pixels.",
  frameDuplicateFillBlank: "Blank other frames",
  frameDuplicateFillBlankHint: "Only the source frame keeps art; others are empty.",
  frameDuplicateConfirm: "Duplicate frames",
  frameCopyFromMenu: "Copy from frame…",
  frameCopyFromOption: (sourceIndex: number) => `Copy from frame ${sourceIndex + 1}`,
  frameCopySuccess: "Frame copied.",
  frameReorderDragHint: "Drag to reorder frames",
  newProjectTitle: "Start a new project",
  newProjectSubtitle: "Choose how you want to begin.",
  newProjectBlankTitle: "Start blank",
  newProjectBlankDescription: "Empty canvas with a resolution preset.",
  newProjectImportTitle: "From image",
  newProjectImportDescription: "Turn a photo or sketch into pixel art.",
  newProjectResolutionLabel: "Canvas size",
  newProjectAnimationLabel: "Animation",
  newProjectAnimationOff: "Single frame",
  newProjectAnimationOffDescription: "Static image — no frame strip.",
  newProjectAnimationOn: "Animated",
  newProjectAnimationOnDescription: "Choose how many frames to start with.",
  newProjectAnimationFrames: (count: number) => `${count} frames`,
  newProjectCreateBlank: "Create project",
  fileMenuNew: "New",
  fileMenuOpen: "Open",
  fileMenuSave: "Save",
  fileMenuSaveAs: "Save As",
  fileMenuExportPng: "Export PNG",
  fileMenuExportSpritesheet: "Export spritesheet",
  fileMenuExportGif: "Export GIF",
  exportOffPaletteTitle: "Some pixels are off-palette",
  exportOffPaletteDescription: (cellCount: number, frameCount: number) =>
    frameCount === 1
      ? `${cellCount} painted cell${cellCount === 1 ? "" : "s"} use a color index that is not in your palette. Export anyway?`
      : `${cellCount} painted cell${cellCount === 1 ? "" : "s"} across ${frameCount} frame${frameCount === 1 ? "" : "s"} use a color index that is not in your palette. Export anyway?`,
  exportOffPaletteCancel: "Cancel",
  exportOffPaletteConfirm: "Export anyway",
  editMenuUndo: "Undo",
  editMenuRedo: "Redo",
  viewMenuShowTechnicalInfo: "Show technical info",
  shortcutsOverlayTitle: "Keyboard shortcuts",
  shortcutsOverlayDescription: "Press Escape or click outside to close.",
  shortcutsOverlayClose: "Close",
  shortcutsOverlayTools: "Tools",
  shortcutsOverlayColors: "Colors",
  shortcutsOverlayEdit: "Edit",
  shortcutsOverlayView: "View",
  shortcutPaint: "Paint",
  shortcutEraser: "Fix mistakes",
  shortcutEyedropper: "Eyedropper",
  shortcutFill: "Fill",
  shortcutLine: "Line",
  shortcutPaletteSlot: (slot: number) => `Select color ${slot}`,
  shortcutUndo: "Undo",
  shortcutRedo: "Redo",
  shortcutShortcutsOverlay: "Show shortcuts",
  shortcutZoomIn: "Zoom in",
  shortcutZoomOut: "Zoom out",
  shortcutZoomFit: "Fit canvas to view",
  projectOpening: "Opening…",
  projectSaving: "Saving…",
  hoverCellTechnical: (
    x: number,
    y: number,
    hex: string,
    index: number,
  ) => `Cell ${x}, ${y} · ${hex} · index ${index}`,
  hoverCellTechnicalTransparent: (x: number, y: number) =>
    `Cell ${x}, ${y} · transparent · index 0`,
  projectOpenTitle: "Open project",
  projectOpenDescription:
    "Enter the path to a .pixelanea file on your computer.",
  projectSaveAsTitle: "Save project as",
  projectSaveAsDescription:
    "Choose where to save this .pixelanea file and what kind of asset it is.",
  projectAssetTypeLabel: "Asset type",
  projectAssetTypeCharacter: "Character",
  projectAssetTypeCharacterHint: "Sprites, avatars, and animated figures",
  projectAssetTypeProp: "Prop",
  projectAssetTypePropHint: "Items, objects, and interactables",
  projectAssetTypeBackground: "Background",
  projectAssetTypeBackgroundHint: "Scenes, tiles, and environment art",
  projectAssetTypeAnimation: "Animation",
  projectAssetTypeAnimationHint: "Multi-frame animated asset",
  projectAssetTypeAnimationDisabledHint:
    "Add more than one frame to save as an animation.",
  projectPathLabel: "File path",
  projectPathPlaceholder: "/home/you/projects/my-art.pixelanea",
  projectPathHint: "Use a path ending in .pixelanea",
  projectOpenConfirm: "Open",
  projectSaveConfirm: "Save",
  projectCancel: "Cancel",
  projectSavedToast: "Project saved.",
  projectOverwriteTitle: "Replace existing file?",
  projectOverwriteDescription:
    "A file at this path may already exist. Saving will replace it.",
  projectOverwriteConfirm: "Replace file",
  discardChangesTitle: "Discard unsaved changes?",
  discardChangesBody:
    "You have changes that aren't saved to a file yet.",
  discardChangesConfirm: "Discard",
  discardChangesCancel: "Keep editing",
  discardChangesSave: "Save, then continue",
  newProjectQuickStart: (width: number, height: number) =>
    `Continue with blank ${width}×${height}`,
  newProjectChooseAgain: "Choose a different path",
  newProjectCanvasSizeHint: "Pick a preset or set a custom width and height.",
  customCanvasSizeLabel: "Custom",
  customCanvasSizeTitle: "Custom canvas size",
  customCanvasSizeDescription: "Set width and height in pixels.",
  customCanvasSizeWidthLabel: "Width",
  customCanvasSizeHeightLabel: "Height",
  customCanvasSizeHint: `Between 1 and 512 pixels per side.`,
  customCanvasSizeConfirm: "Use this size",
  importWizardTitle: "Import image",
  importWizardBack: "Back",
  importWizardNext: "Continue",
  importWizardAccept: "Use this result",
  importWizardStepFile: "Choose image",
  importWizardStepResolution: "Resolution",
  importWizardStepPalette: "Palette",
  importWizardStepPreview: "Preview",
  importWizardStepsLabel: "Import steps",
  importWizardStepCompleted: (step: string) => `${step}, completed`,
  importWizardDropHint: "Drop an image here, or click to browse",
  importWizardDropAccepted: "PNG, JPEG, or BMP",
  importWizardDropPreviewLabel: "Selected image preview",
  importWizardResolutionHint: "Pick the output grid size.",
  importWizardRemoveBackground: "Remove background",
  importWizardRemoveBackgroundHint:
    "Detect the border color and make matching pixels transparent.",
  importWizardRemoveBackgroundOn: "Remove background on",
  importWizardRemoveBackgroundOff: "Remove background off",
  importWizardPaletteHint: "Pick a color palette for quantization.",
  importWizardPreviewHint: "Review the pixelated result before opening the editor.",
  importWizardLoading: "Pixelating…",
  onboardingSkip: "Skip tour",
  onboardingNext: "Next",
  onboardingDone: "Start drawing",
  onboardingStepPickColorTitle: "Pick a color",
  onboardingStepPickColorBody:
    "Choose a swatch in the palette panel on the right.",
  onboardingStepPaintTitle: "Paint your first pixel",
  onboardingStepPaintBody:
    "Click or drag on the canvas. The paint tool is already selected.",
  onboardingStepSaveTitle: "Save when you're ready",
  onboardingStepSaveBody:
    "Use File in the menu bar to save your project locally.",
} as const;
