export const copy = {
  appName: "Pixelanea",
  tagline: "Make pixel art. Keep it local.",
  projectPlaceholder: "Untitled project",
  palettePlaceholder: "Palette swatches will appear here.",
  frameStripPlaceholder: "Frame thumbnails",
  apiConnected: "API connected",
  apiVersion: (version: string) => `Server v${version}`,
  zoomControlsLabel: "Canvas zoom",
  zoomIn: "Zoom in",
  zoomOut: "Zoom out",
  zoomFit: "Fit canvas to view",
  hoverCell: (x: number, y: number) => `Cell ${x}, ${y}`,
  hoverCellNone: "—",
  undo: "Undo",
  redo: "Redo",
  undoRedoToolbarLabel: "Edit history",
  paletteAddColor: "Add color",
  paletteEditColor: "Edit color",
  paletteAddColorTitle: "Add color",
  paletteEditColorTitle: "Edit color",
  paletteAddColorDescription: "Pick a color, then save to add it to your palette.",
  paletteEditColorDescription: "Pick a new color, then save to update the swatch.",
  paletteSaveColor: "Save color",
  paletteColorPickerLabel: "Color picker",
  paletteCancel: "Cancel",
  paletteRemoveColor: "Remove color",
  paletteRemoveInUseTitle: "Remove this color?",
  paletteRemoveInUseDescription:
    "Some pixels on the canvas use this color. Removing it will clear those pixels.",
  paletteRemoveConfirm: "Remove color",
  paletteRemoveCancel: "Keep color",
  paletteDefaultNewColor: "#808080",
} as const;
