#!/usr/bin/env bash
# Regenerate server/tests/fixtures/pixelate_4k_png.inc from pixelate_4k.png
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PNG="${ROOT_DIR}/server/tests/fixtures/pixelate_4k.png"
INC="${ROOT_DIR}/server/tests/fixtures/pixelate_4k_png.inc"

if [[ ! -f "${PNG}" ]]; then
  echo "Missing ${PNG}" >&2
  exit 1
fi

python3 - <<'PY' "${PNG}" "${INC}"
import pathlib
import sys

png_path = pathlib.Path(sys.argv[1])
inc_path = pathlib.Path(sys.argv[2])
data = png_path.read_bytes()

lines = [
    "// Auto-generated by scripts/regen-pixelate-4k-fixture.sh — do not edit.",
    f"// Source: {png_path.name} ({len(data)} bytes)",
    "#pragma once",
    "#include <array>",
    "#include <cstdint>",
    "",
    f"inline constexpr std::array<std::uint8_t, {len(data)}> kPixelate4kPng = {{",
]
row = "  "
for i, byte in enumerate(data):
    row += f"0x{byte:02x}, "
    if (i + 1) % 12 == 0:
        lines.append(row.rstrip())
        row = "  "
if row.strip():
    lines.append(row.rstrip().rstrip(","))
lines.append("};")
lines.append("")

inc_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"Wrote {inc_path} ({len(data)} bytes)")
PY
